services:
  postgres:
    image: postgres:15-alpine
    container_name: api_main_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d api_main_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api_main_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_main_app
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/api_main_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - ./:/app:delegated
      - ~/.m2:/root/.m2
      - ~/.gradle:/root/.gradle            # <-- кеш Gradle
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_main_network

volumes:
    postgres_data:

networks:
    api_main_network: